son = int(input("Istalgan sonni kiriting\n"))
print(son,"ning kvadrati ",son**2,"ga teng")
print(son,"ning kubi ",son**3,"ga teng")
yosh = int(input("yoshingiz nechida ?"))
yil = 2022-yosh
print("Sizning ",yil,"yilda tug'ilgansiz")
son1 = int(input("Istlagan sonni kiriting ="))
son2 = int(input("Istalgan sonni kiriting ="))
print(son1-son2,son1+son2,son1*son2,son1/son2,son1//son2,son1%son2,sep=":")
print(f"{son1}-{son2} =",son1-son2)
print(f"{son1}+{son2} =",son1+son2)
print(f"{son1}*{son2} =",son1*son2)
print(f"{son1}/{son2} =",son1/son2)
print(f"{son1}%{son2} =",son1%son2)
